SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE area;
DROP TABLE candidate;
DROP TABLE candidateresult;
DROP TABLE daaira;
DROP TABLE location;
DROP TABLE electorlist;
DROP TABLE electorlistresult;
DROP TABLE kalam;
DROP TABLE administrativearea;
DROP TABLE user;
DROP TABLE vote;
SET FOREIGN_KEY_CHECKS = 1;